### ISSUE TITLE
Add leakage simulation via Rainbow

### ISSUE THREAD

**Issue by J08nY** [J08nY/pyecsca#19]
Rainbow: https://github.com/Ledger-Donjon/rainbow
can be used to simulate execution of  a binary target (like ARM-Cortex M4 or some x86). The simulated execution can then be used for leakage simulation by applying a given leakage function (+ noise).

Concretely, get inspired by: https://github.com/Ledger-Donjon/rainbow/blob/master/examples/CortexM_AES/cortexm_aes.py

```python
# Given a configuration rendered for Platform.STM32F3 at with the elf at `elf_path` this simulates execution of the main method (which cycles indefinitely waiting for serial input).
# Note that the libc __init functions should be called before, etc..
from rainbow.devices.stm32 import rainbow_stm32f215
e = rainbow_stm32f215(sca_mode=True)
e.load(elf_path, typ=".elf")

e.mem_trace = True
e.trace_regs = True

e.start(e.functions["main"], 0)
```

As the actual chip that ChipWhisperer targets is an STM32F303 (and not an STM32F215 as already in Rainbow), a custom device class for it might be needed. The SVD data for it can be found [here](https://www.st.com/resource/en/svd/stm32f3_svd.zip) and extracted from the XML (.SVD) file. More data on the memory map can be found [here](file:///home/jjan/Downloads/pm0214-stm32-cortexm4-mcus-and-mpus-programming-manual-stmicroelectronics.pdf) or also in the LinkerScript included in the hal directory for the chip.

**Comment by ddddavidee** [comment]
This is a very nice idea.
I tried in the past to implement something similar but I stopped when the binary is dynamically linked to a third-party library (for bigint math, for example)

I'd be interested in having other people ideas and hints on how to emulate a binary depending on external .so files

**Comment by ddddavidee** [comment]
Nice.

I'll try the codegen module!
