### ISSUE TITLE
Integer constants in formula pollute the result coordinates

### ISSUE THREAD

**Issue by scrambler-crypto** [J08nY/pyecsca#7]
Hi,

multiplying a point times the integer one gives float numbers as points coordinates, at least in projective coordinates. 
```python
# define the curve model
secp128r1 = get_params("secg", "secp128r1", "projective")
base = secp128r1.generator
coords = secp128r1.curve.coordinate_model
add = coords.formulas["add-1998-cmo"]
dbl = coords.formulas["dbl-1998-cmo"]
scl = coords.formulas["z"]
mult = LTRMultiplier(add,
                     dbl,
                     scl,
                     always=False,
                     complete=False,
                     short_circuit=True)

scalar = 1
mult.init(secp128r1, base)
pt = mult.multiply(1)
for _ in range(5):
    mult.init(secp128r1, base)
    k = random.getrandbits(128)
    pt = mult.multiply(k)
    mult.init(secp128r1, pt)
    a = mult.multiply(1)
    print(a)
```

gives
```[X=8.375962846509054e+37, Y=2.815641665431342e+38, Z=1]
[X=2.661526430782553e+38, Y=1.1530304631181755e+38, Z=1]
[X=2.0027768112441094e+38, Y=1.209118786786195e+37, Z=1]
[X=2.8478326037726995e+38, Y=1.1501732243886246e+38, Z=1]
[X=7.545866618401884e+37, Y=2.915152976106912e+38, Z=1]
```

Am I doing something wrong? (apart from multiplying by one)

thanks for your work, this library is very very nice.

**Comment by J08nY** [comment]
Interesting, this must have broken quite recently. Will investigate. This does not happen with the GMP integers (install `gmpy2` package and have the GMP library installed).

**Comment by J08nY** [comment]
Got this debugged, the issue is in the handling of formulas, specifically when a formula has something like `Z3 = 1`. The `1` does not get converted into a `Mod` instance and remains as a simple `int`. This then leaks and further makes the arithmetic behave like integer/float arithmetic and not modular. For the time being, the fix is to not use the `scl` formula in this case, as it has such an assignment, and I will work on a fix soon.

**Comment by scrambler-crypto** [comment]
Thanks, installing gmpy2 solves the issue.

**Comment by J08nY** [comment]
> Thanks, installing gmpy2 solves the issue.

I have now pushed a fix that solves this properly.
